### ISSUE TITLE
Link to nRF Asset Tracker for Azure.

### ISSUE THREAD

**Issue by MLopezJ** [NordicSemiconductor/asset-tracker-cloud-device-simulator-azure-js#123]
In readme, the link in `nRF Asset Tracker for Azure` hypertext refers to the same repo: https://github.com/NordicSemiconductor/asset-tracker-cloud-device-simulator-azure-js . Right now it is like a [circular circuit](https://github.com/NordicSemiconductor/asset-tracker-cloud-device-simulator-azure-js/blob/saga/README.md?plain=1#L12). 

I think it should refers to nRF Asset Tracker for Azure: https://github.com/NordicSemiconductor/asset-tracker-cloud-azure-js, as it is in the [AWS repo](https://github.com/NordicSemiconductor/asset-tracker-cloud-device-simulator-aws-js/blob/saga/README.md?plain=1#L12)

@coderbyheart , let me know if I'm correct and it should be updated.

**Comment by coderbyheart** [comment]
Yes, good observation! 👍🏻
